import { Button } from "@teamlead.incubator/ui-kit"
import { Inter } from "next/font/google"
import Head from "next/head"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Foto Flow</title>
        <meta content={"Generated by create next app"} name={"description"} />
        <meta content={"width=device-width, initial-scale=1"} name={"viewport"} />
      </Head>
      <>
        <Button as={Link} href={"/auth/sign-in"} variant={"outlined"}>
          Sign-In
        </Button>
      </>
    </>
  )
}
